# Generated by Django 5.2 on 2025-05-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('url', models.URLField(verbose_name='URL Link')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Clicks')),
            ],
        ),
    ]
